In [290]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [291]:
df=pd.read_csv("credit-approval_csv.csv")
df

A1     A2      A3 A4 A5  A6  A7      A8 A9 A10  A11 A12 A13    A14  \
0      b  30.83   0.000  u  g   w   v   1.250  t   t    1   f   g  202.0   
1      a  58.67   4.460  u  g   q   h   3.040  t   t    6   f   g   43.0   
2      a  24.50   0.500  u  g   q   h   1.500  t   f    0   f   g  280.0   
3      b  27.83   1.540  u  g   w   v   3.750  t   t    5   t   g  100.0   
4      b  20.17   5.625  u  g   w   v   1.710  t   f    0   f   s  120.0   
5      b  32.08   4.000  u  g   m   v   2.500  t   f    0   t   g  360.0   
6      b  33.17   1.040  u  g   r   h   6.500  t   f    0   t   g  164.0   
7      a  22.92  11.585  u  g  cc   v   0.040  t   f    0   f   g   80.0   
8      b  54.42   0.500  y  p   k   h   3.960  t   f    0   f   g  180.0   
9      b  42.50   4.915  y  p   w   v   3.165  t   f    0   t   g   52.0   
10     b  22.08   0.830  u  g   c   h   2.165  f   f    0   t   g  128.0   
11     b  29.92   1.835  u  g   c   h   4.335  t   f    0   f   g  260.0   
12     a  38.25   6.000  u  g   k   v   1.000  t   f    0   t   g    0.0   
13     b  48.08   6.040  u  g   k   v   0.040  f   f    0   f   g    0.0   
14     a  45.83  10.500  u  g   q   v   5.000  t   t    7   t   g    0.0   
15     b  36.67   4.415  y  p   k   v   0.250  t   t   10   t   g  320.0   
16     b  28.25   0.875  u  g   m   v   0.960  t   t    3   t   g  396.0   
17     a  23.25   5.875  u  g   q   v   3.170  t   t   10   f   g  120.0   
18     b  21.83   0.250  u  g   d   h   0.665  t   f    0   t   g    0.0   
19     a  19.17   8.585  u  g  cc   h   0.750  t   t    7   f   g   96.0   
20     b  25.00  11.250  u  g   c   v   2.500  t   t   17   f   g  200.0   
21     b  23.25   1.000  u  g   c   v   0.835  t   f    0   f   s  300.0   
22     a  47.75   8.000  u  g   c   v   7.875  t   t    6   t   g    0.0   
23     a  27.42  14.500  u  g   x   h   3.085  t   t    1   f   g  120.0   
24     a  41.17   6.500  u  g   q   v   0.500  t   t    3   t   g  145.0   
25     a  15.83   0.585  u  g   c   h   1.500  t   t    2   f   g  100.0   
26     a  47.00  13.000  u  g   i  bb   5.165  t   t    9   t   g    0.0   
27     b  56.58  18.500  u  g   d  bb  15.000  t   t   17   t   g    0.0   
28     b  57.42   8.500  u  g   e   h   7.000  t   t    3   f   g    0.0   
29     b  42.08   1.040  u  g   w   v   5.000  t   t    6   t   g  500.0   
..   ...    ...     ... .. ..  ..  ..     ... ..  ..  ...  ..  ..    ...   
660    b  22.25   9.000  u  g  aa   v   0.085  f   f    0   f   g    0.0   
661    b  29.83   3.500  u  g   c   v   0.165  f   f    0   f   g  216.0   
662    a  23.50   1.500  u  g   w   v   0.875  f   f    0   t   g  160.0   
663    b  32.08   4.000  y  p  cc   v   1.500  f   f    0   t   g  120.0   
664    b  31.08   1.500  y  p   w   v   0.040  f   f    0   f   s  160.0   
665    b  31.83   0.040  y  p   m   v   0.040  f   f    0   f   g    0.0   
666    a  21.75  11.750  u  g   c   v   0.250  f   f    0   t   g  180.0   
667    a  17.92   0.540  u  g   c   v   1.750  f   t    1   t   g   80.0   
668    b  30.33   0.500  u  g   d   h   0.085  f   f    0   t   s  252.0   
669    b  51.83   2.040  y  p  ff  ff   1.500  f   f    0   f   g  120.0   
670    b  47.17   5.835  u  g   w   v   5.500  f   f    0   f   g  465.0   
671    b  25.83  12.835  u  g  cc   v   0.500  f   f    0   f   g    0.0   
672    a  50.25   0.835  u  g  aa   v   0.500  f   f    0   t   g  240.0   
673  NaN  29.50   2.000  y  p   e   h   2.000  f   f    0   f   g  256.0   
674    a  37.33   2.500  u  g   i   h   0.210  f   f    0   f   g  260.0   
675    a  41.58   1.040  u  g  aa   v   0.665  f   f    0   f   g  240.0   
676    a  30.58  10.665  u  g   q   h   0.085  f   t   12   t   g  129.0   
677    b  19.42   7.250  u  g   m   v   0.040  f   t    1   f   g  100.0   
678    a  17.92  10.210  u  g  ff  ff   0.000  f   f    0   f   g    0.0   
679    a  20.08   1.250  u  g   c   v   0.000  f   f    0   f   g    0.0   
680    b  19.50   0.290  u  g   k   v   0.290  f   f  

In [292]:
x=df[['A1','A2','A3','A4','A5','A6','A7','A8','A9','A10','A11','A12','A13','A14','A15']]
y=df['class']

In [293]:
x.head(20)

A1     A2      A3 A4 A5  A6 A7     A8 A9 A10  A11 A12 A13    A14    A15
0   b  30.83   0.000  u  g   w  v  1.250  t   t    1   f   g  202.0      0
1   a  58.67   4.460  u  g   q  h  3.040  t   t    6   f   g   43.0    560
2   a  24.50   0.500  u  g   q  h  1.500  t   f    0   f   g  280.0    824
3   b  27.83   1.540  u  g   w  v  3.750  t   t    5   t   g  100.0      3
4   b  20.17   5.625  u  g   w  v  1.710  t   f    0   f   s  120.0      0
5   b  32.08   4.000  u  g   m  v  2.500  t   f    0   t   g  360.0      0
6   b  33.17   1.040  u  g   r  h  6.500  t   f    0   t   g  164.0  31285
7   a  22.92  11.585  u  g  cc  v  0.040  t   f    0   f   g   80.0   1349
8   b  54.42   0.500  y  p   k  h  3.960  t   f    0   f   g  180.0    314
9   b  42.50   4.915  y  p   w  v  3.165  t   f    0   t   g   52.0   1442
10  b  22.08   0.830  u  g   c  h  2.165  f   f    0   t   g  128.0      0
11  b  29.92   1.835  u  g   c  h  4.335  t   f    0   f   g  260.0    200
12  a  38.25   6.000  u  g   k  v  1.000  t   f    0   t   g    0.0      0
13  b  48.08   6.040  u  g   k  v  0.040  f   f    0   f   g    0.0   2690
14  a  45.83  10.500  u  g   q  v  5.000  t   t    7   t   g    0.0      0
15  b  36.67   4.415  y  p   k  v  0.250  t   t   10   t   g  320.0      0
16  b  28.25   0.875  u  g   m  v  0.960  t   t    3   t   g  396.0      0
17  a  23.25   5.875  u  g   q  v  3.170  t   t   10   f   g  120.0    245
18  b  21.83   0.250  u  g   d  h  0.665  t   f    0   t   g    0.0      0
19  a  19.17   8.585  u  g  cc  h  0.750  t   t    7   f   g   96.0      0

In [294]:
y.head(20)

0     +
1     +
2     +
3     +
4     +
5     +
6     +
7     +
8     +
9     +
10    +
11    +
12    +
13    +
14    +
15    +
16    +
17    +
18    +
19    +
Name: class, dtype: object

In [295]:
x.A4.value_counts()

u    519
y    163
l      2
Name: A4, dtype: int64

In [296]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
#le.fit(['u','y','l'])
#le.transform(['u','y','l'])
x.head(20)

A1     A2      A3 A4 A5  A6 A7     A8 A9 A10  A11 A12 A13    A14    A15
0   b  30.83   0.000  u  g   w  v  1.250  t   t    1   f   g  202.0      0
1   a  58.67   4.460  u  g   q  h  3.040  t   t    6   f   g   43.0    560
2   a  24.50   0.500  u  g   q  h  1.500  t   f    0   f   g  280.0    824
3   b  27.83   1.540  u  g   w  v  3.750  t   t    5   t   g  100.0      3
4   b  20.17   5.625  u  g   w  v  1.710  t   f    0   f   s  120.0      0
5   b  32.08   4.000  u  g   m  v  2.500  t   f    0   t   g  360.0      0
6   b  33.17   1.040  u  g   r  h  6.500  t   f    0   t   g  164.0  31285
7   a  22.92  11.585  u  g  cc  v  0.040  t   f    0   f   g   80.0   1349
8   b  54.42   0.500  y  p   k  h  3.960  t   f    0   f   g  180.0    314
9   b  42.50   4.915  y  p   w  v  3.165  t   f    0   t   g   52.0   1442
10  b  22.08   0.830  u  g   c  h  2.165  f   f    0   t   g  128.0      0
11  b  29.92   1.835  u  g   c  h  4.335  t   f    0   f   g  260.0    200
12  a  38.25   6.000  u  g   k  v  1.000  t   f    0   t   g    0.0      0
13  b  48.08   6.040  u  g   k  v  0.040  f   f    0   f   g    0.0   2690
14  a  45.83  10.500  u  g   q  v  5.000  t   t    7   t   g    0.0      0
15  b  36.67   4.415  y  p   k  v  0.250  t   t   10   t   g  320.0      0
16  b  28.25   0.875  u  g   m  v  0.960  t   t    3   t   g  396.0      0
17  a  23.25   5.875  u  g   q  v  3.170  t   t   10   f   g  120.0    245
18  b  21.83   0.250  u  g   d  h  0.665  t   f    0   t   g    0.0      0
19  a  19.17   8.585  u  g  cc  h  0.750  t   t    7   f   g   96.0      0

In [297]:
le.fit(['u','y','l'])

LabelEncoder()

In [298]:
le.transform(['l','u','y'])

array([0, 1, 2])

In [299]:
x['A4'].fillna('l',inplace = True)

/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py:6130: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)


In [300]:
x['A4']=le.transform(x.A4)

/home/beast/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [301]:
x.A5.value_counts()

g     519
p     163
gg      2
Name: A5, dtype: int64

In [302]:
le.fit(['g','p','gg'])

LabelEncoder()

In [303]:
le.transform(['gg','p','g'])

array([1, 2, 0])

In [304]:
x.A5.isna().sum()

6

In [305]:
x['A5'].fillna('p',inplace = True)

In [306]:
x['A5']=le.transform(x.A5)

/home/beast/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [61]:
x.head(20)

A1     A2      A3  A4  A5  A6 A7     A8 A9 A10  A11 A12 A13    A14    A15
0   b  30.83   0.000   1   0   w  v  1.250  t   t    1   f   g  202.0      0
1   a  58.67   4.460   1   0   q  h  3.040  t   t    6   f   g   43.0    560
2   a  24.50   0.500   1   0   q  h  1.500  t   f    0   f   g  280.0    824
3   b  27.83   1.540   1   0   w  v  3.750  t   t    5   t   g  100.0      3
4   b  20.17   5.625   1   0   w  v  1.710  t   f    0   f   s  120.0      0
5   b  32.08   4.000   1   0   m  v  2.500  t   f    0   t   g  360.0      0
6   b  33.17   1.040   1   0   r  h  6.500  t   f    0   t   g  164.0  31285
7   a  22.92  11.585   1   0  cc  v  0.040  t   f    0   f   g   80.0   1349
8   b  54.42   0.500   2   2   k  h  3.960  t   f    0   f   g  180.0    314
9   b  42.50   4.915   2   2   w  v  3.165  t   f    0   t   g   52.0   1442
10  b  22.08   0.830   1   0   c  h  2.165  f   f    0   t   g  128.0      0
11  b  29.92   1.835   1   0   c  h  4.335  t   f    0   f   g  260.0    200
12  a  38.25   6.000   1   0   k  v  1.000  t   f    0   t   g    0.0      0
13  b  48.08   6.040   1   0   k  v  0.040  f   f    0   f   g    0.0   2690
14  a  45.83  10.500   1   0   q  v  5.000  t   t    7   t   g    0.0      0
15  b  36.67   4.415   2   2   k  v  0.250  t   t   10   t   g  320.0      0
16  b  28.25   0.875   1   0   m  v  0.960  t   t    3   t   g  396.0      0
17  a  23.25   5.875   1   0   q  v  3.170  t   t   10   f   g  120.0    245
18  b  21.83   0.250   1   0   d  h  0.665  t   f    0   t   g    0.0      0
19  a  19.17   8.585   1   0  cc  h  0.750  t   t    7   f   g   96.0      0

In [307]:
x.A6.value_counts()

c     137
q      78
w      64
i      59
aa     54
ff     53
k      51
cc     41
x      38
m      38
d      30
e      25
j      10
r       3
Name: A6, dtype: int64

In [308]:
le.fit(['c','q','w','i','aa','ff','k','cc','x','m','d','e','j','r'])

LabelEncoder()

In [309]:
le.transform(['c','q','w','i','aa','ff','k','cc','x','m','d','e','j','r'])

array([ 1, 10, 12,  6,  0,  5,  8,  2, 13,  9,  3,  4,  7, 11])

In [310]:
x.A6.isna().sum()

9

In [311]:
x['A6'].fillna('r',inplace = True)

In [312]:
x['A6']=le.transform(x.A6)

/home/beast/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [313]:
x.head(20)

A1     A2      A3  A4  A5  A6 A7     A8 A9 A10  A11 A12 A13    A14    A15
0   b  30.83   0.000   1   0  12  v  1.250  t   t    1   f   g  202.0      0
1   a  58.67   4.460   1   0  10  h  3.040  t   t    6   f   g   43.0    560
2   a  24.50   0.500   1   0  10  h  1.500  t   f    0   f   g  280.0    824
3   b  27.83   1.540   1   0  12  v  3.750  t   t    5   t   g  100.0      3
4   b  20.17   5.625   1   0  12  v  1.710  t   f    0   f   s  120.0      0
5   b  32.08   4.000   1   0   9  v  2.500  t   f    0   t   g  360.0      0
6   b  33.17   1.040   1   0  11  h  6.500  t   f    0   t   g  164.0  31285
7   a  22.92  11.585   1   0   2  v  0.040  t   f    0   f   g   80.0   1349
8   b  54.42   0.500   2   2   8  h  3.960  t   f    0   f   g  180.0    314
9   b  42.50   4.915   2   2  12  v  3.165  t   f    0   t   g   52.0   1442
10  b  22.08   0.830   1   0   1  h  2.165  f   f    0   t   g  128.0      0
11  b  29.92   1.835   1   0   1  h  4.335  t   f    0   f   g  260.0    200
12  a  38.25   6.000   1   0   8  v  1.000  t   f    0   t   g    0.0      0
13  b  48.08   6.040   1   0   8  v  0.040  f   f    0   f   g    0.0   2690
14  a  45.83  10.500   1   0  10  v  5.000  t   t    7   t   g    0.0      0
15  b  36.67   4.415   2   2   8  v  0.250  t   t   10   t   g  320.0      0
16  b  28.25   0.875   1   0   9  v  0.960  t   t    3   t   g  396.0      0
17  a  23.25   5.875   1   0  10  v  3.170  t   t   10   f   g  120.0    245
18  b  21.83   0.250   1   0   3  h  0.665  t   f    0   t   g    0.0      0
19  a  19.17   8.585   1   0   2  h  0.750  t   t    7   f   g   96.0      0

In [314]:
x.A7.value_counts()

v     399
h     138
bb     59
ff     57
z       8
j       8
dd      6
n       4
o       2
Name: A7, dtype: int64

In [315]:
le.fit(['v','h','bb','ff','z','j','dd','n','o'])

LabelEncoder()

In [316]:
le.transform(['v','h','bb','ff','z','j','dd','n','o'])

array([7, 3, 0, 2, 8, 4, 1, 5, 6])

In [317]:
x.A7.isna().sum()

9

In [318]:
x['A7'].fillna('o',inplace = True)

In [319]:
x['A7']=le.transform(x.A7)

/home/beast/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [320]:
x.A7.value_counts()

7    399
3    138
0     59
2     57
6     11
8      8
4      8
1      6
5      4
Name: A7, dtype: int64

In [321]:
x.A9.value_counts()

t    361
f    329
Name: A9, dtype: int64

In [322]:
le.fit(['t','f'])

LabelEncoder()

In [323]:
le.transform(['f','t'])

array([0, 1])

In [324]:
x.A9.isna().sum()

0

In [325]:
x['A9']=le.transform(x.A9)

/home/beast/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [326]:
x.head(20)

A1     A2      A3  A4  A5  A6  A7     A8  A9 A10  A11 A12 A13    A14    A15
0   b  30.83   0.000   1   0  12   7  1.250   1   t    1   f   g  202.0      0
1   a  58.67   4.460   1   0  10   3  3.040   1   t    6   f   g   43.0    560
2   a  24.50   0.500   1   0  10   3  1.500   1   f    0   f   g  280.0    824
3   b  27.83   1.540   1   0  12   7  3.750   1   t    5   t   g  100.0      3
4   b  20.17   5.625   1   0  12   7  1.710   1   f    0   f   s  120.0      0
5   b  32.08   4.000   1   0   9   7  2.500   1   f    0   t   g  360.0      0
6   b  33.17   1.040   1   0  11   3  6.500   1   f    0   t   g  164.0  31285
7   a  22.92  11.585   1   0   2   7  0.040   1   f    0   f   g   80.0   1349
8   b  54.42   0.500   2   2   8   3  3.960   1   f    0   f   g  180.0    314
9   b  42.50   4.915   2   2  12   7  3.165   1   f    0   t   g   52.0   1442
10  b  22.08   0.830   1   0   1   3  2.165   0   f    0   t   g  128.0      0
11  b  29.92   1.835   1   0   1   3  4.335   1   f    0   f   g  260.0    200
12  a  38.25   6.000   1   0   8   7  1.000   1   f    0   t   g    0.0      0
13  b  48.08   6.040   1   0   8   7  0.040   0   f    0   f   g    0.0   2690
14  a  45.83  10.500   1   0  10   7  5.000   1   t    7   t   g    0.0      0
15  b  36.67   4.415   2   2   8   7  0.250   1   t   10   t   g  320.0      0
16  b  28.25   0.875   1   0   9   7  0.960   1   t    3   t   g  396.0      0
17  a  23.25   5.875   1   0  10   7  3.170   1   t   10   f   g  120.0    245
18  b  21.83   0.250   1   0   3   3  0.665   1   f    0   t   g    0.0      0
19  a  19.17   8.585   1   0   2   3  0.750   1   t    7   f   g   96.0      0

In [327]:
x.A10.value_counts()

f    395
t    295
Name: A10, dtype: int64

In [328]:
le.fit(['f','t'])

LabelEncoder()

In [329]:
le.transform(['f','t'])

array([0, 1])

In [330]:
x.A10.isna().sum()

0

In [331]:
x['A10']=le.transform(x.A10)

/home/beast/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [332]:
x.head(20)

A1     A2      A3  A4  A5  A6  A7     A8  A9  A10  A11 A12 A13    A14  \
0   b  30.83   0.000   1   0  12   7  1.250   1    1    1   f   g  202.0   
1   a  58.67   4.460   1   0  10   3  3.040   1    1    6   f   g   43.0   
2   a  24.50   0.500   1   0  10   3  1.500   1    0    0   f   g  280.0   
3   b  27.83   1.540   1   0  12   7  3.750   1    1    5   t   g  100.0   
4   b  20.17   5.625   1   0  12   7  1.710   1    0    0   f   s  120.0   
5   b  32.08   4.000   1   0   9   7  2.500   1    0    0   t   g  360.0   
6   b  33.17   1.040   1   0  11   3  6.500   1    0    0   t   g  164.0   
7   a  22.92  11.585   1   0   2   7  0.040   1    0    0   f   g   80.0   
8   b  54.42   0.500   2   2   8   3  3.960   1    0    0   f   g  180.0   
9   b  42.50   4.915   2   2  12   7  3.165   1    0    0   t   g   52.0   
10  b  22.08   0.830   1   0   1   3  2.165   0    0    0   t   g  128.0   
11  b  29.92   1.835   1   0   1   3  4.335   1    0    0   f   g  260.0   
12  a  38.25   6.000   1   0   8   7  1.000   1    0    0   t   g    0.0   
13  b  48.08   6.040   1   0   8   7  0.040   0    0    0   f   g    0.0   
14  a  45.83  10.500   1   0  10   7  5.000   1    1    7   t   g    0.0   
15  b  36.67   4.415   2   2   8   7  0.250   1    1   10   t   g  320.0   
16  b  28.25   0.875   1   0   9   7  0.960   1    1    3   t   g  396.0   
17  a  23.25   5.875   1   0  10   7  3.170   1    1   10   f   g  120.0   
18  b  21.83   0.250   1   0   3   3  0.665   1    0    0   t   g    0.0   
19  a  19.17   8.585   1   0   2   3  0.750   1    1    7   f   g   96.0   

      A15  
0       0  
1     560  
2     824  
3       3  
4       0  
5       0  
6   31285  
7    1349  
8     314  
9    1442  
10      0  
11    200  
12      0  
13   2690  
14      0  
15      0  
16      0  
17    245  
18      0  
19      0

In [333]:
x.A12.value_counts()

f    374
t    316
Name: A12, dtype: int64

In [334]:
x.A12=le.transform(x.A12)

/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py:5096: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value


In [335]:
x.head(20)

A1     A2      A3  A4  A5  A6  A7     A8  A9  A10  A11  A12 A13    A14  \
0   b  30.83   0.000   1   0  12   7  1.250   1    1    1    0   g  202.0   
1   a  58.67   4.460   1   0  10   3  3.040   1    1    6    0   g   43.0   
2   a  24.50   0.500   1   0  10   3  1.500   1    0    0    0   g  280.0   
3   b  27.83   1.540   1   0  12   7  3.750   1    1    5    1   g  100.0   
4   b  20.17   5.625   1   0  12   7  1.710   1    0    0    0   s  120.0   
5   b  32.08   4.000   1   0   9   7  2.500   1    0    0    1   g  360.0   
6   b  33.17   1.040   1   0  11   3  6.500   1    0    0    1   g  164.0   
7   a  22.92  11.585   1   0   2   7  0.040   1    0    0    0   g   80.0   
8   b  54.42   0.500   2   2   8   3  3.960   1    0    0    0   g  180.0   
9   b  42.50   4.915   2   2  12   7  3.165   1    0    0    1   g   52.0   
10  b  22.08   0.830   1   0   1   3  2.165   0    0    0    1   g  128.0   
11  b  29.92   1.835   1   0   1   3  4.335   1    0    0    0   g  260.0   
12  a  38.25   6.000   1   0   8   7  1.000   1    0    0    1   g    0.0   
13  b  48.08   6.040   1   0   8   7  0.040   0    0    0    0   g    0.0   
14  a  45.83  10.500   1   0  10   7  5.000   1    1    7    1   g    0.0   
15  b  36.67   4.415   2   2   8   7  0.250   1    1   10    1   g  320.0   
16  b  28.25   0.875   1   0   9   7  0.960   1    1    3    1   g  396.0   
17  a  23.25   5.875   1   0  10   7  3.170   1    1   10    0   g  120.0   
18  b  21.83   0.250   1   0   3   3  0.665   1    0    0    1   g    0.0   
19  a  19.17   8.585   1   0   2   3  0.750   1    1    7    0   g   96.0   

      A15  
0       0  
1     560  
2     824  
3       3  
4       0  
5       0  
6   31285  
7    1349  
8     314  
9    1442  
10      0  
11    200  
12      0  
13   2690  
14      0  
15      0  
16      0  
17    245  
18      0  
19      0

In [336]:
x.A13.value_counts()

g    625
s     57
p      8
Name: A13, dtype: int64

In [337]:
x.A13.isna().sum()

0

In [338]:
le.fit(['g','s','p'])

LabelEncoder()

In [339]:
le.transform(['g','s','p'])

array([0, 2, 1])

In [340]:
x['A13']=le.transform(x.A13)

/home/beast/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [341]:
x.head(20)

A1     A2      A3  A4  A5  A6  A7     A8  A9  A10  A11  A12  A13    A14  \
0   b  30.83   0.000   1   0  12   7  1.250   1    1    1    0    0  202.0   
1   a  58.67   4.460   1   0  10   3  3.040   1    1    6    0    0   43.0   
2   a  24.50   0.500   1   0  10   3  1.500   1    0    0    0    0  280.0   
3   b  27.83   1.540   1   0  12   7  3.750   1    1    5    1    0  100.0   
4   b  20.17   5.625   1   0  12   7  1.710   1    0    0    0    2  120.0   
5   b  32.08   4.000   1   0   9   7  2.500   1    0    0    1    0  360.0   
6   b  33.17   1.040   1   0  11   3  6.500   1    0    0    1    0  164.0   
7   a  22.92  11.585   1   0   2   7  0.040   1    0    0    0    0   80.0   
8   b  54.42   0.500   2   2   8   3  3.960   1    0    0    0    0  180.0   
9   b  42.50   4.915   2   2  12   7  3.165   1    0    0    1    0   52.0   
10  b  22.08   0.830   1   0   1   3  2.165   0    0    0    1    0  128.0   
11  b  29.92   1.835   1   0   1   3  4.335   1    0    0    0    0  260.0   
12  a  38.25   6.000   1   0   8   7  1.000   1    0    0    1    0    0.0   
13  b  48.08   6.040   1   0   8   7  0.040   0    0    0    0    0    0.0   
14  a  45.83  10.500   1   0  10   7  5.000   1    1    7    1    0    0.0   
15  b  36.67   4.415   2   2   8   7  0.250   1    1   10    1    0  320.0   
16  b  28.25   0.875   1   0   9   7  0.960   1    1    3    1    0  396.0   
17  a  23.25   5.875   1   0  10   7  3.170   1    1   10    0    0  120.0   
18  b  21.83   0.250   1   0   3   3  0.665   1    0    0    1    0    0.0   
19  a  19.17   8.585   1   0   2   3  0.750   1    1    7    0    0   96.0   

      A15  
0       0  
1     560  
2     824  
3       3  
4       0  
5       0  
6   31285  
7    1349  
8     314  
9    1442  
10      0  
11    200  
12      0  
13   2690  
14      0  
15      0  
16      0  
17    245  
18      0  
19      0

In [342]:
y.value_counts()

-    383
+    307
Name: class, dtype: int64

In [343]:
le.fit(['+','-'])

LabelEncoder()

In [344]:
le.transform(['+','-'])

array([0, 1])

In [345]:
y.isna().sum()

0

In [346]:
y=le.transform(y)

In [347]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [348]:
x.A1.value_counts()

b    468
a    210
Name: A1, dtype: int64

In [349]:
le.fit(['a','b'])

LabelEncoder()

In [350]:
le.transform(['a','b'])

array([0, 1])

In [351]:
x.A1.isna().sum()

12

In [352]:
x['A1'].fillna('a',inplace = True)

In [353]:
x.A1=le.transform(x.A1)

In [354]:
x.A2.isna().sum()

12

In [356]:
x['A2'].fillna('0.00',inplace = True)

In [357]:
x.A14.isna().sum()

13

In [358]:
x['A14'].fillna('0.00',inplace= True)

In [359]:
x.A15.isna().sum()

0

In [360]:
df=x

In [364]:
df['class']=y
df.head(20)

A1     A2      A3  A4  A5  A6  A7     A8  A9  A10  A11  A12  A13  A14  \
0    1  30.83   0.000   1   0  12   7  1.250   1    1    1    0    0  202   
1    0  58.67   4.460   1   0  10   3  3.040   1    1    6    0    0   43   
2    0   24.5   0.500   1   0  10   3  1.500   1    0    0    0    0  280   
3    1  27.83   1.540   1   0  12   7  3.750   1    1    5    1    0  100   
4    1  20.17   5.625   1   0  12   7  1.710   1    0    0    0    2  120   
5    1  32.08   4.000   1   0   9   7  2.500   1    0    0    1    0  360   
6    1  33.17   1.040   1   0  11   3  6.500   1    0    0    1    0  164   
7    0  22.92  11.585   1   0   2   7  0.040   1    0    0    0    0   80   
8    1  54.42   0.500   2   2   8   3  3.960   1    0    0    0    0  180   
9    1   42.5   4.915   2   2  12   7  3.165   1    0    0    1    0   52   
10   1  22.08   0.830   1   0   1   3  2.165   0    0    0    1    0  128   
11   1  29.92   1.835   1   0   1   3  4.335   1    0    0    0    0  260   
12   0  38.25   6.000   1   0   8   7  1.000   1    0    0    1    0    0   
13   1  48.08   6.040   1   0   8   7  0.040   0    0    0    0    0    0   
14   0  45.83  10.500   1   0  10   7  5.000   1    1    7    1    0    0   
15   1  36.67   4.415   2   2   8   7  0.250   1    1   10    1    0  320   
16   1  28.25   0.875   1   0   9   7  0.960   1    1    3    1    0  396   
17   0  23.25   5.875   1   0  10   7  3.170   1    1   10    0    0  120   
18   1  21.83   0.250   1   0   3   3  0.665   1    0    0    1    0    0   
19   0  19.17   8.585   1   0   2   3  0.750   1    1    7    0    0   96   

      A15  class  
0       0      0  
1     560      0  
2     824      0  
3       3      0  
4       0      0  
5       0      0  
6   31285      0  
7    1349      0  
8     314      0  
9    1442      0  
10      0      0  
11    200      0  
12      0      0  
13   2690      0  
14      0      0  
15      0      0  
16      0      0  
17    245      0  
18      0      0  
19      0      0

In [365]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [366]:
len(x_train)

552

In [367]:
len(y_train)

552

In [368]:
len(x_test)

138

In [369]:
len(y_test)

138

In [371]:
from sklearn import svm
model=svm.SVC(gamma=0.0001,C=100)

In [372]:
model.fit(x_train,y_train)

SVC(C=100, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.0001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [373]:
model.predict(x_test)

array([1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 0])

In [374]:
model.score(x_test,y_test)

0.7971014492753623